### ISSUE TITLE
Please reconsider to not use mpv ipc

### ISSUE THREAD

**Issue by joectchan** [xi/cplay-ng#5]
This [post](https://www.reddit.com/r/termux/comments/gwfs6t/how_to_listen_to_music_with_playaudio/) mention how to use cplay-ng in termux to invoke `play-audio` as a minimalist audio player.

I was able to edit cplay.py, locate the 'mpv' python list, replace it with `['play-audio', self.path]`. That worked for me.

I read the latest change in your repo, which begins to use mpv ipc. I feel that this future direction makes cplay-ng depend on mpv too much. Please re-consider again. Thanks.

**Comment by xi** [comment]
I dropped support for all backends except mpv in 4.0.0. I did that because for me at least, the theoretical benefits did not outweigh the complexity.

Fortunately, there are different versions of cplay with different focus. I can recommend [andreasvc/cplay](https://github.com/andreasvc/cplay). It is actively maintained and we sometimes share patches.

I will keep open minded about this though. For now I want to stay with mpv, but when more arguments show up I might reconsider.
