### ISSUE TITLE
Cplay-ng manual

### ISSUE THREAD

**Issue by Nilsonfsilva** [xi/cplay-ng#6]
I am packing Cplay-ng for debian repository. Following the policies of debian in a manual I am sending it in case you want to include in the next versions.
Thank you
[manual_cplay-ng.txt](https://github.com/xi/cplay-ng/files/7878618/manual_cplay-ng.txt)

**Comment by xi** [comment]
nice to hear that you want to package cplay-ng for debian. I feel honored!

There actually had been a [man page for cplay in the past](https://github.com/xi/cplay-ng/commits/main/cplay.1), but I intentionally removed it to avoid duplicating documentation. Consequently I don't want to re-introduce one to the repository.

Regarding your version I still have some feedback:

- The tagline for the project is "simple curses audio player", not "minimalist music player with a textual user"
- cplay-ng does not take any command line arguments (since 4.0)
- I am not the original author of cplay, I only maintain this fork. The full list of authors is available in the AUTHORS file.
- The link for reporting bugs should be https://github.com/xi/cplay-ng/issues

I hope this feedback helps and I am looking forward to having cplay-ng in debian!
